language: minimal

script:

  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

  # Run tests.
  - tests/tests.sh

  # Run installer/updater
  # Debug mode downloads files from this branch to ./debug folder
  - ./update.sh --debug --branch $BRANCH

  # Diff main Makefile
  - diff debug/Makefile make/Makefile.project.dist

  # Test that downloaded files exist
  - test -f debug/tools/make/amazeeio.mk
  - test -f debug/tools/make/common.mk
  - test -f debug/tools/make/composer.mk
  - test -f debug/tools/make/docker.mk
  - test -f debug/tools/make/drupal.mk
  - test -f debug/tools/make/include.mk
  - test -f debug/tools/make/javascript.mk
  - test -f debug/tools/make/Makefile
  - test -f debug/tools/make/qa.mk
