name: Tests

on: [push]

jobs:

  test:

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Show make version
        run: make --version

      - name: Make sure we have docker binary (even if faked)
        run: command -v docker > /dev/null 2>&1 || (touch /usr/local/bin/docker && chmod +x /usr/local/bin/docker)

      - name: Show make debug
        run: cd make && make debug

      - name: Run tests
        run: tests/tests.sh

      - name: Create file to be removed
        run: mkdir -p debug/tools/make && touch debug/tools/make/druid-cli.mk

      # Debug mode downloads files from this branch to ./debug folder
      - name: Run updater
        run: ./update.sh --debug --branch ${GITHUB_REF##*/}

      - name: Test that downloaded files exist in debug folder
        run: |
          test -f debug/tools/make/lagoon.mk
          test -f debug/tools/make/common.mk
          test -f debug/tools/make/composer.mk
          test -f debug/tools/make/docker.mk
          test -f debug/tools/make/drupal.mk
          test -f debug/tools/make/include.mk
          test -f debug/tools/make/javascript.mk
          test -f debug/tools/make/Makefile
          test -f debug/tools/make/qa.mk
          test -f debug/tools/make/symfony.mk
          test -f debug/tools/make/utils.mk
          test -f debug/tools/make/wordpress.mk

      - name: Test that removed file does not exist in debug folder
        run: test ! -f debug/tools/make/druid-cli.mk

      - name: Diff main Makefile
        run: diff debug/Makefile make/Makefile.project.dist
